trigger:
  branches:
    include:
      - dev
      - uat
      - prod


pool:
  vmImage: ubuntu-latest


variables:
  buildConfiguration: Release


# ==========================
# BUILD STAGE
# ==========================

stages:

- stage: Build

  displayName: Build Application


  jobs:

  - job: Build_App

    displayName: Build Angular and .NET API


    steps:


    # Install .NET SDK
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '8.x'


    # Restore and Build API
    - task: DotNetCoreCLI@2
      displayName: Build API
      inputs:
        command: publish
        projects: '**/ABCPharmacy.API.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api'


    # Install Node
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'


    # Build Angular
    - script: |

        cd ABCPharmacy.UI

        npm install

        npm run build -- --configuration production

      displayName: Build Angular



    # Publish API Artifact
    - task: PublishBuildArtifacts@1
      inputs:

        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'

        ArtifactName: api



    # Publish Angular Artifact
    - task: PublishBuildArtifacts@1
      inputs:

        PathtoPublish: 'ABCPharmacy.UI/dist'

        ArtifactName: angular





# ==========================
# DEV DEPLOYMENT
# ==========================

- stage: Deploy_DEV

  displayName: Deploy DEV


  dependsOn: Build


  condition:

    eq(variables['Build.SourceBranch'], 'refs/heads/dev')



  jobs:


  - deployment: Deploy_API_DEV

    displayName: Deploy API DEV


    environment: DEV


    strategy:

      runOnce:

        deploy:

          steps:


          - download: current

            artifact: api


          - task: AzureWebApp@1

            inputs:

              azureSubscription: Azure-ServiceConnection

              appName: ABC-Pharmacy-API-DEV

              package: $(Pipeline.Workspace)/api





  - deployment: Deploy_UI_DEV

    displayName: Deploy Angular DEV


    environment: DEV


    strategy:

      runOnce:

        deploy:

          steps:


          - download: current

            artifact: angular


          - task: AzureWebApp@1

            inputs:

              azureSubscription: Azure-ServiceConnection

              appName: ABC-Pharmacy-UI-DEV

              package: $(Pipeline.Workspace)/angular







# ==========================
# UAT DEPLOYMENT
# ==========================

- stage: Deploy_UAT


  displayName: Deploy UAT


  dependsOn: Build


  condition:

    eq(variables['Build.SourceBranch'], 'refs/heads/uat')



  jobs:


  - deployment: Deploy_API_UAT


    environment: UAT


    strategy:

      runOnce:

        deploy:

          steps:


          - download: current

            artifact: api


          - task: AzureWebApp@1

            inputs:

              azureSubscription: Azure-ServiceConnection

              appName: ABC-Pharmacy-API-UAT

              package: $(Pipeline.Workspace)/api






  - deployment: Deploy_UI_UAT


    environment: UAT


    strategy:

      runOnce:

        deploy:

          steps:


          - download: current

            artifact: angular


          - task: AzureWebApp@1

            inputs:

              azureSubscription: Azure-ServiceConnection

              appName: ABC-Pharmacy-UI-UAT

              package: $(Pipeline.Workspace)/angular







# ==========================
# PROD DEPLOYMENT
# ==========================

- stage: Deploy_PROD


  displayName: Deploy PROD


  dependsOn: Build


  condition:

    eq(variables['Build.SourceBranch'], 'refs/heads/prod')



  jobs:


  - deployment: Deploy_API_PROD


    environment: PROD


    strategy:

      runOnce:

        deploy:

          steps:


          - download: current

            artifact: api


          - task: AzureWebApp@1

            inputs:

              azureSubscription: Azure-ServiceConnection

              appName: ABC-Pharmacy-API-PROD

              package: $(Pipeline.Workspace)/api






  - deployment: Deploy_UI_PROD


    environment: PROD


    strategy:

      runOnce:

        deploy:

          steps:


          - download: current

            artifact: angular


          - task: AzureWebApp@1

            inputs:

              azureSubscription: Azure-ServiceConnection

              appName: ABC-Pharmacy-UI-PROD

              package: $(Pipeline.Workspace)/angular
